Rails.application.routes.draw do
  get '/courses', to: 'courses#index'
  get 'instructors/index'
  get 'instructors/edit'
  get 'instructors/new'
  get 'instructors/show'
  get 'cohort/index'
  get 'cohort/edit'
  get 'cohort/new'
  get 'cohort/show'
  get 'student/index'
  get 'student/edit'
  get 'student/new'
  get 'student/show'
  get 'students/index'
  get 'students/edit'
  get 'students/new'
  get 'students/show'
  get 'instructor/index'
  get 'instructor/edit'
  get 'instructor/new'
  get 'instructor/show'
  get 'course/index'
  get 'course/edit'
  get 'course/new'
  get 'course/show'
  get 'courses/index'
  get 'courses/edit'
  get 'courses/new'
  get 'courses/show'
  get 'cohorts/index'
  get 'cohorts/edit'
  get 'cohorts/new'
  get 'cohorts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
